version: '3.8'

services:
  db:
    image: docker.io/library/mysql:8.0
    container_name: notebook_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root    
      MYSQL_DATABASE: notebook                    
      MYSQL_USER: notebook_user                   
      MYSQL_PASSWORD: notebook_user        
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: